[app]
name = "cloud-search"
mode = "debug"
level = "info"
http_listen = "80"
url = "0.0.0.0:30080"
pprof = false
params = false
logger = "/home/logs/app"
version = "1.0.0"

[mongodb]
dsn = "mongodb://admin:123456@127.0.0.1:27017"
conn_time_out= 10
conn_max_pool_size= 10

[mysql]
dsn = "root:root@tcp(127.0.0.1:3306)/xthk_devops?charset=utf8&parseTime=True&loc=Local"
db_name = "xthk_devops"
max_idle_conn = 10
max_open_conn = 100
conn_max_lifetime = 6

[git]
Key = "#########"
url = "https://gitlab.com"
gitlab_depod_name = "app_gitlab"
gitlab_code_name = "code_list"
gitlab_project_name = "project_list"
key_end = 600

[redis]
addr = "127.0.0.1:6379"
db = 10
password = ""
min_idle_conns = 5
pool_size = 500
pool_timeout = 2
idle_timeout = 10
token_expired = 7200 # expired time 2*60*60
